export const AUTH_TYPE = {
  LOGIN: "LOGIN",
  ACTIVATE: "ACTIVATE",
  LOGOUT: "LOGOUT",
  GENERATE_OTP: "GENERATE_OTP",
  VERIFY_OTP: "VERIFY_OTP",
  VALIDATE_OTP: "VALIDATE_OTP",
  DISABLE_OTP: "DISABLE_OTP",
};
